from pydantic import AliasChoices
from sqlmodel import Field,SQLModel,create_engine,select,Session
from typing import Any, Literal

from enum import Enum

class PriorityLevel(str,Enum):
    LOW="low"
    MEDIUM="medium"
    HIGH="high"
    

class emails(SQLModel,table=True):
    id:int | None = Field(default=None,primary_key=True)
    gmail_message_id:str | None = Field(unique=True)
    subject:str | None = Field(default="No Subject")
    sender:str | None
    body:str | None = Field()

class agent_analysis(SQLModel,table=True):
    id:int | None = Field(default=None,primary_key=True)
    gmail_message_id:str | None = Field(unique=True)
    subject:str | None = Field(default="No Subject")
    sender:str | None = None
    body:str | None = Field()
    needs_reply:str | None = None
    category:PriorityLevel | None = None
    summary:str | None = None

class agent_draft_replies(SQLModel, table=True):
    id : int | None = Field(default=None,primary_key=True)
    subject: str | None = Field(description='subject for the email')
    sender:str = Field(description='the receipient mail id')
    draft_reply:str = Field(description='the draft reply generated by the agent')

class main_database:
    def __init__(self,database:str="database.db"):
        self.database = database
        self.engine = create_engine(f"sqlite:///{self.database}") 
        SQLModel.metadata.create_all(self.engine)
    
    def insert(self,message=dict[str,Any]) -> str:
        
        self.message = message
        self.entry_to_main_database = emails(gmail_message_id=self.message['gmail_message_id'],
                                             subject=self.message['subject'],
                                             sender=self.message['sender'],
                                             body=self.message['body'])
        
        with Session(self.engine) as session:
            session.add(self.entry_to_main_database) # adding to the db
            session.commit()
        
        return "added to database"
    
    def exist(self,gmail_message_id:str):
        
        with Session(self.engine) as session:
            statement = select(emails).where(emails.gmail_message_id==gmail_message_id)
            result = session.exec(statement).first()
        
        return bool(result)
    
    def fetch_multiples(self,limit:int=5):
        self.limit = limit
        self.latest_emails = None
        
        with Session(self.engine) as session:
            self.statement = select(emails).order_by(emails.id.desc()).limit(self.limit)
            self.results = session.exec(self.statement)
            self.latest_emails = self.results.all()

        return self.latest_emails
    
    def fetch_one(self,limit:int=1):
        self.limit = limit
        
        with Session(self.engine) as session:
            self.statement = select(emails).order_by(emails.id.desc()).limit(limit)
            self.results = session.exec(self.statement)
            self.latest_emails = self.results.first()

        return self.latest_emails
            
    
class agent_records_database:
    def __init__(self,database:str="agent_records.db"):
        self.database = database
        self.engine = create_engine(f"sqlite:///{self.database}") 
        SQLModel.metadata.create_all(self.engine)
        
    def insert(self,message=dict[str,Any]) -> str:
        
        self.message = message

        
        self.entry_to_agent_records = agent_analysis(gmail_message_id=self.message['gmail_message_id'],
                                             subject=self.message['subject'],
                                             sender=self.message['sender'],
                                             body=self.message['body'],
                                             needs_reply=self.message['needs_reply'],
                                             category=self.message['category'],
                                             summary=self.message['summary'])
        
        with Session(self.engine) as session:
            session.add(self.entry_to_agent_records) # adding to the db
            session.commit()
        
        return "added to agent records"
    
    def view(self,limit:int=5): # by default top 5 row visible only

        self.limit = limit
        self.agent_record_only_5 = None
        
        with Session(self.engine) as session:
            self.statement = select(agent_analysis).limit(5)
            self.results = session.exec(self.statement)
            self.agent_record_only_5 = self.results.all()

        return self.agent_record_only_5
    
    def view_top_first(self): # by default return the first row of the table/assuming the latest entry

        agent_record_first = None
        
        with Session(self.engine) as session:
            statement = select(agent_analysis).order_by(agent_analysis.id.desc()).limit(1)
            results = session.exec(statement)
            agent_record_first = results.first()

        return agent_record_first

class agent_reply_database:
    def __init__(self,database:str="agent_drafts.db"):
        self.database = database
        self.engine = create_engine(f"sqlite:///{self.database}")
        SQLModel.metadata.create_all(self.engine) # necessary to create the tables
        
    def insert(self,message:dict[str,Any]) -> str:
        self.entry_to_the_draft_records = agent_draft_replies(subject=message['subject'],
                                                              sender=message['sender'],
                                                              draft_reply=message['draft_reply'])
        
        try :
            with Session(self.engine) as session:
                session.add(self.entry_to_the_draft_records)
                session.commit()
            
            return "data added to the database!"
        except Exception as e:
            return f"something went wrong : {e}"
        
    def view(self,limit:int=1):
        
        agent_row = None
        
        try:
            with Session(self.engine) as session:
                statement = select(agent_draft_replies).order_by(agent_draft_replies.id.desc()).limit(limit)
                result = session.exec(statement)
                agent_row = result.first()
            return agent_row
        except Exception as e:
            return f"something went wrong while fetching the top row : {e}"